In [1]:
import pandas as pd

In [2]:
pci_1 = pd.read_csv("pci_al-fl.csv")
pci_1.set_index("DATE", inplace = True)
pci_1.head()

,ALPCPI,AKPCPI,AZPCPI,ARPCPI,CAPCPI,COPCPI,CTPCPI,DEPCPI,DCPCPI,FLPCPI
DATE,,,,,,,,,,
2016-01-01,39536.0,56302.0,40801.0,40385.0,58048.0,52475.0,69919.0,48836.0,77828.0,46073.0
2017-01-01,41030.0,57394.0,42590.0,41657.0,60549.0,55604.0,71740.0,50798.0,79221.0,48504.0
2018-01-01,42710.0,60355.0,44597.0,43325.0,63720.0,58896.0,74855.0,52930.0,81243.0,50964.0
2019-01-01,44145.0,62806.0,46058.0,44629.0,66619.0,61157.0,77289.0,54485.0,83406.0,52426.0

In [3]:
pci_2 = pd.read_csv("pci_ga-me.csv")
pci_2.set_index("DATE", inplace = True)
pci_2.head()

,GAPCPI,HIPCPI,IDPCPI,ILPCPI,INPCPI,IAPCPI,KSPCPI,KYPCPI,LAPCPI,MEPCPI
DATE,,,,,,,,,,
2016-01-01,42896.0,51170.0,40567.0,52417.0,43672.0,46547.0,47390.0,39754.0,42528.0,44832.0
2017-01-01,44894.0,53433.0,42268.0,54252.0,45244.0,47662.0,48883.0,40904.0,43932.0,46565.0
2018-01-01,46957.0,55214.0,44554.0,57145.0,47321.0,50175.0,51261.0,42338.0,46207.0,48792.0
2019-01-01,48236.0,57015.0,45968.0,58764.0,48678.0,51865.0,53426.0,43770.0,47460.0,50634.0

In [4]:
pci_3 = pd.read_csv("pci_md-nh.csv")
pci_3.set_index("DATE", inplace = True)
pci_3.head()

,MDPCPI,MAPCPI,MIPCPI,MNPCPI,MSPCPI,MOPCPI,MTPCPI,NEPCPI,NVPCPI,NHPCPI
DATE,,,,,,,,,,
2016-01-01,59011.0,65725.0,44637.0,53083.0,35672.0,44318.0,44024.0,49615.0,45351.0,56513.0
2017-01-01,60758.0,68442.0,45948.0,54960.0,36536.0,45342.0,46199.0,50645.0,47650.0,58759.0
2018-01-01,62708.0,71801.0,47777.0,57371.0,37852.0,47109.0,48194.0,52890.0,50000.0,61471.0
2019-01-01,64640.0,74187.0,49228.0,58834.0,38914.0,48656.0,49747.0,54515.0,51161.0,63502.0

In [5]:
pci_4 = pd.read_csv("pci_nj-ri.csv")
pci_4.set_index("DATE", inplace = True)
pci_4.head()

,NJPCPI,NMPCPI,NYPCPI,NCPCPI,NDPCPI,OHPCPI,OKPCPI,ORPCPI,PAPCPI,RIPCPI
DATE,,,,,,,,,,
2016-01-01,62842.0,39025.0,61401.0,42816.0,51832.0,45226.0,41887.0,46586.0,51818.0,50655.0
2017-01-01,64983.0,39747.0,65814.0,44409.0,52736.0,46829.0,43794.0,48762.0,53306.0,52644.0
2018-01-01,67845.0,41670.0,68657.0,46216.0,55788.0,48747.0,45843.0,51500.0,56032.0,54431.0
2019-01-01,70471.0,43326.0,71717.0,47766.0,57232.0,50199.0,47341.0,53191.0,58032.0,56361.0

In [6]:
pci_5 = pd.read_csv("pci_sc-wy.csv")
pci_5.set_index("DATE", inplace = True)
pci_5.head()

,SCPCPI,SDPCPI,TNPCPI,TXPCPI,UTPCPI,VTPCPI,VAPCPI,WAPCPI,WVPCPI,WIPCPI,WYPCPI
DATE,,,,,,,,,,,
2016-01-01,40569.0,48724.0,43626.0,45803.0,42375.0,50420.0,53792.0,55802.0,37099.0,47598.0,54168.0
2017-01-01,42227.0,49787.0,45233.0,48394.0,44178.0,51697.0,55631.0,58437.0,38927.0,49264.0,56524.0
2018-01-01,43912.0,52633.0,47210.0,51136.0,47008.0,53531.0,57964.0,62209.0,41192.0,51628.0,60689.0
2019-01-01,45438.0,53962.0,48684.0,52813.0,48939.0,55293.0,59657.0,64758.0,42315.0,53227.0,62189.0

In [7]:
pci_by_state_cleaned = pd.concat([pci_1, pci_2, pci_3, pci_4, pci_5], axis=1).head()
pci_by_state_cleaned.head()

,ALPCPI,AKPCPI,AZPCPI,ARPCPI,CAPCPI,COPCPI,CTPCPI,DEPCPI,DCPCPI,FLPCPI,...,SDPCPI,TNPCPI,TXPCPI,UTPCPI,VTPCPI,VAPCPI,WAPCPI,WVPCPI,WIPCPI,WYPCPI
DATE,,,,,,,,,,,,,,,,,,,,,
2016-01-01,39536.0,56302.0,40801.0,40385.0,58048.0,52475.0,69919.0,48836.0,77828.0,46073.0,...,48724.0,43626.0,45803.0,42375.0,50420.0,53792.0,55802.0,37099.0,47598.0,54168.0
2017-01-01,41030.0,57394.0,42590.0,41657.0,60549.0,55604.0,71740.0,50798.0,79221.0,48504.0,...,49787.0,45233.0,48394.0,44178.0,51697.0,55631.0,58437.0,38927.0,49264.0,56524.0
2018-01-01,42710.0,60355.0,44597.0,43325.0,63720.0,58896.0,74855.0,52930.0,81243.0,50964.0,...,52633.0,47210.0,51136.0,47008.0,53531.0,57964.0,62209.0,41192.0,51628.0,60689.0
2019-01-01,44145.0,62806.0,46058.0,44629.0,66619.0,61157.0,77289.0,54485.0,83406.0,52426.0,...,53962.0,48684.0,52813.0,48939.0,55293.0,59657.0,64758.0,42315.0,53227.0,62189.0

In [8]:
pci_by_state_cleaned = pci_by_state_cleaned.transpose()
print(pci_by_state_cleaned)

DATE    2016-01-01  2017-01-01  2018-01-01  2019-01-01
ALPCPI     39536.0     41030.0     42710.0     44145.0
AKPCPI     56302.0     57394.0     60355.0     62806.0
AZPCPI     40801.0     42590.0     44597.0     46058.0
ARPCPI     40385.0     41657.0     43325.0     44629.0
CAPCPI     58048.0     60549.0     63720.0     66619.0
COPCPI     52475.0     55604.0     58896.0     61157.0
CTPCPI     69919.0     71740.0     74855.0     77289.0
DEPCPI     48836.0     50798.0     52930.0     54485.0
DCPCPI     77828.0     79221.0     81243.0     83406.0
FLPCPI     46073.0     48504.0     50964.0     52426.0
GAPCPI     42896.0     44894.0     46957.0     48236.0
HIPCPI     51170.0     53433.0     55214.0     57015.0
IDPCPI     40567.0     42268.0     44554.0     45968.0
ILPCPI     52417.0     54252.0     57145.0     58764.0
INPCPI     43672.0     45244.0     47321.0     48678.0
IAPCPI     46547.0     47662.0     50175.0     51865.0
KSPCPI     47390.0     48883.0     51261.0     53426.0
KYPCPI     39754.0     40904.0     42338.0     43770.0
LAPCPI     42528.0     43932.0     46207.0     47460.0
MEPCPI     44832.0     46565.0     48792.0     50634.0
MDPCPI     59011.0     60758.0     62708.0     64640.0
MAPCPI     65725.0     68442.0     71801.0     74187.0
MIPCPI     44637.0     45948.0     47777.0     49228.0
MNPCPI     53083.0     54960.0     57371.0     58834.0
MSPCPI     35672.0     36536.0     37852.0     38914.0
MOPCPI     44318.0     45342.0     47109.0     48656.0
MTPCPI     44024.0     46199.0     48194.0     49747.0
NEPCPI     49615.0     50645.0     52890.0     54515.0
NVPCPI     45351.0     47650.0     50000.0     51161.0
NHPCPI     56513.0     58759.0     61471.0     63502.0
NJPCPI     62842.0     64983.0     67845.0     70471.0
NMPCPI     39025.0     39747.0     41670.0     43326.0
NYPCPI     61401.0     65814.0     68657.0     71717.0
NCPCPI     42816.0     44409.0     46216.0     47766.0
NDPCPI     51832.0     52736.0     55788.0     57232.0
OHPCPI     45226.0     46829.0     48747.0     50199.0
OKPCPI     41887.0     43794.0     45843.0     47341.0
ORPCPI     46586.0     48762.0     51500.0     53191.0
PAPCPI     51818.0     53306.0     56032.0     58032.0
RIPCPI     50655.0     52644.0     54431.0     56361.0
SCPCPI     40569.0     42227.0     43912.0     45438.0
SDPCPI     48724.0     49787.0     52633.0     53962.0
TNPCPI     43626.0     45233.0     47210.0     48684.0
TXPCPI     45803.0     48394.0     51136.0     52813.0
UTPCPI     42375.0     44178.0     47008.0     48939.0
VTPCPI     50420.0     51697.0     53531.0     55293.0
VAPCPI     53792.0     55631.0     57964.0     59657.0
WAPCPI     55802.0     58437.0     62209.0     64758.0
WVPCPI     37099.0     38927.0     41192.0     42315.0
WIPCPI     47598.0     49264.0     51628.0     53227.0
WYPCPI     54168.0     56524.0     60689.0     62189.0

In [9]:
pci_by_state_cleaned.dtypes

DATE
2016-01-01    float64
2017-01-01    float64
2018-01-01    float64
2019-01-01    float64
dtype: object

In [11]:
pci_by_state_cleaned = pci_by_state_cleaned.rename(columns = {'2016-01-01': '2016', '2017-01-01': '2017', '2018-01-01': '2018', '2019-01-01': '2019'})
print (pci_by_state_cleaned)

DATE       2016     2017     2018     2019
ALPCPI  39536.0  41030.0  42710.0  44145.0
AKPCPI  56302.0  57394.0  60355.0  62806.0
AZPCPI  40801.0  42590.0  44597.0  46058.0
ARPCPI  40385.0  41657.0  43325.0  44629.0
CAPCPI  58048.0  60549.0  63720.0  66619.0
COPCPI  52475.0  55604.0  58896.0  61157.0
CTPCPI  69919.0  71740.0  74855.0  77289.0
DEPCPI  48836.0  50798.0  52930.0  54485.0
DCPCPI  77828.0  79221.0  81243.0  83406.0
FLPCPI  46073.0  48504.0  50964.0  52426.0
GAPCPI  42896.0  44894.0  46957.0  48236.0
HIPCPI  51170.0  53433.0  55214.0  57015.0
IDPCPI  40567.0  42268.0  44554.0  45968.0
ILPCPI  52417.0  54252.0  57145.0  58764.0
INPCPI  43672.0  45244.0  47321.0  48678.0
IAPCPI  46547.0  47662.0  50175.0  51865.0
KSPCPI  47390.0  48883.0  51261.0  53426.0
KYPCPI  39754.0  40904.0  42338.0  43770.0
LAPCPI  42528.0  43932.0  46207.0  47460.0
MEPCPI  44832.0  46565.0  48792.0  50634.0
MDPCPI  59011.0  60758.0  62708.0  64640.0
MAPCPI  65725.0  68442.0  71801.0  74187.0
MIPCPI  44637.0  45948.0  47777.0  49228.0
MNPCPI  53083.0  54960.0  57371.0  58834.0
MSPCPI  35672.0  36536.0  37852.0  38914.0
MOPCPI  44318.0  45342.0  47109.0  48656.0
MTPCPI  44024.0  46199.0  48194.0  49747.0
NEPCPI  49615.0  50645.0  52890.0  54515.0
NVPCPI  45351.0  47650.0  50000.0  51161.0
NHPCPI  56513.0  58759.0  61471.0  63502.0
NJPCPI  62842.0  64983.0  67845.0  70471.0
NMPCPI  39025.0  39747.0  41670.0  43326.0
NYPCPI  61401.0  65814.0  68657.0  71717.0
NCPCPI  42816.0  44409.0  46216.0  47766.0
NDPCPI  51832.0  52736.0  55788.0  57232.0
OHPCPI  45226.0  46829.0  48747.0  50199.0
OKPCPI  41887.0  43794.0  45843.0  47341.0
ORPCPI  46586.0  48762.0  51500.0  53191.0
PAPCPI  51818.0  53306.0  56032.0  58032.0
RIPCPI  50655.0  52644.0  54431.0  56361.0
SCPCPI  40569.0  42227.0  43912.0  45438.0
SDPCPI  48724.0  49787.0  52633.0  53962.0
TNPCPI  43626.0  45233.0  47210.0  48684.0
TXPCPI  45803.0  48394.0  51136.0  52813.0
UTPCPI  42375.0  44178.0  47008.0  48939.0
VTPCPI  50420.0  51697.0  53531.0  55293.0
VAPCPI  53792.0  55631.0  57964.0  59657.0
WAPCPI  55802.0  58437.0  62209.0  64758.0
WVPCPI  37099.0  38927.0  41192.0  42315.0
WIPCPI  47598.0  49264.0  51628.0  53227.0
WYPCPI  54168.0  56524.0  60689.0  62189.0

In [12]:
pci_by_state_cleaned.to_csv(r'pci_by_state_cleaned.csv')